-- MySQL Script generated by MySQL Workbench
-- sáb 27 out 2018 19:38:48 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema heroku_ecafce692810fca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema heroku_ecafce692810fca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `heroku_ecafce692810fca` DEFAULT CHARACTER SET utf8 ;
USE `heroku_ecafce692810fca` ;

-- -----------------------------------------------------
-- Table `heroku_ecafce692810fca`.`hibernate_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_ecafce692810fca`.`hibernate_sequence` (
  `next_val` BIGINT(20) NULL DEFAULT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_ecafce692810fca`.`type_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_ecafce692810fca`.`type_user` (
  `idtype_user` INT(11) NOT NULL,
  `desc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtype_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_ecafce692810fca`.`user_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_ecafce692810fca`.`user_image` (
  `id` INT NOT NULL,
  `imate` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_ecafce692810fca`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_ecafce692810fca`.`user` (
  `id` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `user_image_id` VARCHAR(11) NULL,
  `desc` VARCHAR(255) NULL,
  `user_image_id` INT NOT NULL,
  `type_user_idtype_user` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_type_user_idx` (`type_user_idtype_user` ASC) VISIBLE,
  INDEX `fk_user_user_image1_idx` (`user_image_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_ecafce692810fca`.`timeline_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_ecafce692810fca`.`timeline_image` (
  `idtimeline_image` INT NOT NULL,
  `image` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`idtimeline_image`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_ecafce692810fca`.`timeline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_ecafce692810fca`.`timeline` (
  `idtimeline` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `text` VARCHAR(1000) NOT NULL,
  `datetime` VARCHAR(45) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `timeline_image_idtimeline_image`  NULL,
  PRIMARY KEY (`idtimeline`),
  INDEX `fk_timeline_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_timeline_timeline_image1_idx` (`timeline_image_idtimeline_image` ASC) VISIBLE,
  CONSTRAINT `fk_timeline_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `heroku_ecafce692810fca`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_timeline_timeline_image1`
    FOREIGN KEY (`timeline_image_idtimeline_image`)
    REFERENCES `heroku_ecafce692810fca`.`timeline_image` (`idtimeline_image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_ecafce692810fca`.`knowledge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_ecafce692810fca`.`knowledge` (
  `id` INT NOT NULL,
  `knowledgecol` VARCHAR(64) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_ecafce692810fca`.`rel_user_knowledge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_ecafce692810fca`.`rel_user_knowledge` (
  `idrel_user_knowledge` INT NOT NULL,
  `user_id` INT NOT NULL,
  `knowledge_id` INT NOT NULL,
  PRIMARY KEY (`idrel_user_knowledge`),
  INDEX `fk_rel_user_knowledge_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_rel_user_knowledge_knowledge1_idx` (`knowledge_id` ASC) VISIBLE,
  CONSTRAINT `fk_rel_user_knowledge_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `heroku_ecafce692810fca`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rel_user_knowledge_knowledge1`
    FOREIGN KEY (`knowledge_id`)
    REFERENCES `heroku_ecafce692810fca`.`knowledge` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_ecafce692810fca`.`lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_ecafce692810fca`.`lesson` (
  `id` INT NOT NULL COMMENT '	',
  `title` VARCHAR(64) NOT NULL,
  `desc` VARCHAR(255) NOT NULL,
  `video` VARCHAR(255) NOT NULL,
  `rel_user_knowledge_idrel_user_knowledge` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lesson_rel_user_knowledge1_idx` (`rel_user_knowledge_idrel_user_knowledge` ASC) VISIBLE,
  CONSTRAINT `fk_lesson_rel_user_knowledge1`
    FOREIGN KEY (`rel_user_knowledge_idrel_user_knowledge`)
    REFERENCES `heroku_ecafce692810fca`.`rel_user_knowledge` (`idrel_user_knowledge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
