-- MySQL Script generated by MySQL Workbench
-- sáb 10 nov 2018 18:59:53 -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema heroku_ecafce692810fca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema heroku_ecafce692810fca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `heroku_ecafce692810fca` DEFAULT CHARACTER SET utf8 ;
USE `heroku_ecafce692810fca` ;

-- -----------------------------------------------------
-- Table `heroku_ecafce692810fca`.`hibernate_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_ecafce692810fca`.`hibernate_sequence` (
  `next_val` BIGINT(20) NOT NULL,
  PRIMARY KEY (`next_val`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_ecafce692810fca`.`knowledge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_ecafce692810fca`.`knowledge` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_ecafce692810fca`.`type_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_ecafce692810fca`.`type_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_ecafce692810fca`.`user_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_ecafce692810fca`.`user_image` (
  `id` INT(11) NOT NULL,
  `image` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_ecafce692810fca`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_ecafce692810fca`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `pwd` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `type_user_id` INT(11) NOT NULL,
  `user_image_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `type_user_id` (`type_user_id` ASC) VISIBLE,
  INDEX `fk_user_user_image1_idx` (`user_image_id` ASC) VISIBLE,
  CONSTRAINT `user_ibfk_2`
    FOREIGN KEY (`type_user_id`)
    REFERENCES `heroku_ecafce692810fca`.`type_user` (`id`),
  CONSTRAINT `fk_user_user_image1`
    FOREIGN KEY (`user_image_id`)
    REFERENCES `heroku_ecafce692810fca`.`user_image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_ecafce692810fca`.`rel_user_knowledge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_ecafce692810fca`.`rel_user_knowledge` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `knowledge_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rel_user_knowledge_user1` (`user_id` ASC) VISIBLE,
  INDEX `fk_rel_user_knowledge_knowledge1` (`knowledge_id` ASC) VISIBLE,
  CONSTRAINT `fk_rel_user_knowledge_knowledge1`
    FOREIGN KEY (`knowledge_id`)
    REFERENCES `heroku_ecafce692810fca`.`knowledge` (`id`),
  CONSTRAINT `fk_rel_user_knowledge_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `heroku_ecafce692810fca`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_ecafce692810fca`.`lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_ecafce692810fca`.`lesson` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(64) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `video` VARCHAR(255) NOT NULL,
  `date` DATETIME NOT NULL,
  `rel_user_knowledge_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lesson_rel_user_knowledge1` (`rel_user_knowledge_id` ASC) VISIBLE,
  CONSTRAINT `fk_lesson_rel_user_knowledge1`
    FOREIGN KEY (`rel_user_knowledge_id`)
    REFERENCES `heroku_ecafce692810fca`.`rel_user_knowledge` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_ecafce692810fca`.`timeline_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_ecafce692810fca`.`timeline_image` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `image` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_ecafce692810fca`.`timeline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_ecafce692810fca`.`timeline` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `text` VARCHAR(1000) NOT NULL,
  `date` DATETIME NOT NULL,
  `user_id` INT(11) NOT NULL,
  `timeline_image_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_timeline_user1` (`user_id` ASC) VISIBLE,
  INDEX `fk_timeline_timeline_image1` (`timeline_image_id` ASC) VISIBLE,
  CONSTRAINT `fk_timeline_timeline_image1`
    FOREIGN KEY (`timeline_image_id`)
    REFERENCES `heroku_ecafce692810fca`.`timeline_image` (`id`),
  CONSTRAINT `fk_timeline_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `heroku_ecafce692810fca`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_ecafce692810fca`.`user_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_ecafce692810fca`.`user_image` (
  `id` INT(11) NOT NULL,
  `image` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
